apiVersion: v1
kind: Namespace
metadata:
  name: chatty
---
apiVersion: v1
kind: Secret
metadata:
  namespace: chatty
  name: chatty
type: Opaque
data:
  OPENAI_API_KEY: <base64 encoded key>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: chatty
  name: chatty
  labels:
    app: chatty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatty
  template:
    metadata:
      labels:
        app: chatty
    spec:
      containers:
        - name: chatty
          image: <docker user>/chatbot-ui:latest
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chatbot-ui
                  key: OPENAI_API_KEY
---
kind: Service
apiVersion: v1
metadata:
  namespace: chatty
  name: chatty
  labels:
    app: chatty
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: chatty
  type: ClusterIP
